import React from 'react'
import Head from 'next/head'
import 'src/styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
    <React.Fragment>
        <Head>
          <link rel="icon" href="/favicon.ico" />
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Component {...pageProps} />
    </React.Fragment>
  );
}

export default MyApp
