import React from 'react'
import Head from 'next/head'
import 'src/styles/globals.css'
import { useCounter } from 'src/hooks/useCounter';
import { useInputArray } from 'src/hooks/useInputArray';
import { useBgColor } from 'src/hooks/useBgColor';

function MyApp({ Component, pageProps }) {
  const counter = useCounter();
  const inputArray = useInputArray();
  useBgColor()

  return (
    <React.Fragment>
        <Head>
          <link rel="icon" href="/favicon.ico" />
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Component {...pageProps} {...counter} {...inputArray} />
    </React.Fragment>
  );
}

export default MyApp
