import React from 'react'
import Head from 'next/head'
import 'src/styles/globals.css'
import { Layout } from 'src/components/Layout';

const MyApp = ({ Component, pageProps }) => {

  return (
    <React.Fragment>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout><Component {...pageProps} /></Layout>
    </React.Fragment>
  );
}

export default MyApp
