import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { HeadLine }  from '../components/Headline'
import { Footer } from '../components/Footer'
import { Links }  from '../components/Links'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeadLine title="Index Page" page="index.js"/>
        <Links />
      </main>

    <Footer />
    </div>
  )
}
